# Generated by Django 2.2.4 on 2019-08-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jesuspokerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='jesuspokerapi.Player'),
        ),
    ]
