# Generated by Django 2.2.4 on 2019-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesuspokerapi', '0003_session_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionresult',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
