# Generated by Django 2.2.4 on 2019-09-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesuspokerapi', '0004_auto_20190904_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='creator',
        ),
        migrations.AlterField(
            model_name='session',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
